# -*- coding: utf-8 -*-
"""E03_pooled_logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PyP-QmK1FoquO9Ffnae7dY7rZrMPchJe
"""

# ==========================================
# E3: Pooled (Universal) Logistic Regression
# Trains ONE Logistic Regression on pooled (all-season) training data,
# evaluates it on each of the 4 season-specific test sets separately.
# Test sets are IDENTICAL to E1/E2 (same time-based 80/20 split per
# season) so results are directly comparable across E1/E2/E3.
# ==========================================
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, roc_auc_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

# ---- Same predictors / target / seasons as E1 & E2 ----
predictors = [
    'AQI_lag24', 'Raw_Conc_lag24', 'Hour', 'Month', 'DayOfWeek',
    'temperature_2m', 'relativehumidity_2m', 'dewpoint_2m', 'apparent_temperature',
    'precipitation', 'rain', 'surface_pressure', 'cloudcover', 'cloudcover_low',
    'cloudcover_mid', 'cloudcover_high', 'windspeed_10m', 'winddirection_10m',
    'windgusts_10m', 'et0_fao_evapotranspiration', 'vapor_pressure_deficit',
    'shortwave_radiation', 'direct_radiation', 'diffuse_radiation', 'weathercode'
]
target = 'Hazard_Tier'
seasons = ['winter', 'summer', 'monsoon', 'post_monsoon']

def calc_gmean(y_true, y_pred):
    report = classification_report(y_true, y_pred, output_dict=True)
    recalls = [report[cls]['recall'] for cls in report if cls not in ['accuracy', 'macro avg', 'weighted avg']]
    return np.exp(np.mean(np.log(np.maximum(recalls, 1e-5))))

# ==========================================
# STEP 1: Load each season, apply the SAME time-based 80/20 split as E1.
# ==========================================
# NOTE: Pinned to absolute /content path. Earlier cells (E2's git clone +
# os.chdir into model subfolders) can leave stray duplicate copies of
# files with the SAME NAME elsewhere in the filesystem. A relative-path
# search-by-filename can silently grab the wrong one depending on
# whatever the current working directory happens to be. Loading by
# absolute path removes that ambiguity entirely.
UPLOAD_DIR = "/content"

print("--- [E3-LR STEP 1] Loading seasonal CSVs & applying identical time-based split ---")
print(f"Current working directory: {os.getcwd()}")
print(f"Loading files from fixed absolute path: {UPLOAD_DIR}\n")

raw_train_frames_X = []
raw_train_frames_y = []
season_test_sets = {}  # season -> raw test X/y, kept UNTOUCHED, same as E1/E2

for season in seasons:
    possible_names = [f"{season}.csv", f"data_{season}.csv", f"dhaka_{season}.csv"]
    file_path = None
    for name in possible_names:
        candidate = os.path.join(UPLOAD_DIR, name)
        if os.path.exists(candidate):
            file_path = candidate
            break
    if file_path is None:
        raise FileNotFoundError(
            f"Could not find CSV for '{season}' in {UPLOAD_DIR}. "
            f"Expected one of: {possible_names}. "
            f"If your uploaded files live elsewhere, update UPLOAD_DIR above."
        )

    df = pd.read_csv(file_path)

    # Identical time-based 80/20 split logic to E1
    split_idx = int(len(df) * 0.8)
    train_df = df.iloc[:split_idx]
    test_df = df.iloc[split_idx:]

    raw_train_frames_X.append(train_df[predictors])
    raw_train_frames_y.append(train_df[target])

    season_test_sets[season] = {
        'X_test_raw': test_df[predictors],
        'y_test_raw': test_df[target]
    }

    nan_count = df[predictors].isna().sum().sum()
    if nan_count > 0:
        raise ValueError(
            f"[{season}] Loaded file '{file_path}' contains {nan_count} NaN values "
            f"in predictor columns. This likely means the wrong file was loaded "
            f"(a stale duplicate elsewhere in the filesystem). Verify UPLOAD_DIR "
            f"points to your freshly uploaded CSVs, not a git-cloned copy."
        )

    print(f"[{season.capitalize():<12}] Loaded '{file_path}' | Train rows: {len(train_df)} | Test rows: {len(test_df)} | NaNs: {nan_count}")

# ==========================================
# STEP 2: Build the POOLED training set (raw, before scaling/SMOTE)
# ==========================================
print("\n--- [E3-LR STEP 2] Building pooled (universal) training set ---")

X_pool_raw = pd.concat(raw_train_frames_X, axis=0).reset_index(drop=True)
y_pool_raw = pd.concat(raw_train_frames_y, axis=0).reset_index(drop=True)

print(f"Pooled training set size: {X_pool_raw.shape[0]} rows (sum of all 4 seasons' train splits)")
print(f"Pooled class distribution:\n{y_pool_raw.value_counts()}")

# ==========================================
# STEP 3: Fit ONE new scaler on pooled training data.
# Transform pooled train AND each season's test set with THIS scaler.
# ==========================================
print("\n--- [E3-LR STEP 3] Fitting pooled StandardScaler ---")

pooled_scaler = StandardScaler()
X_pool_scaled = pooled_scaler.fit_transform(X_pool_raw)

for season in seasons:
    X_te_raw = season_test_sets[season]['X_test_raw']
    season_test_sets[season]['X_test_scaled'] = pooled_scaler.transform(X_te_raw)

# ==========================================
# STEP 4: Apply SMOTE ONCE on the pooled (scaled) training set
# ==========================================
print("\n--- [E3-LR STEP 4] Applying SMOTE to pooled training set ---")

smote = SMOTE(random_state=42)
X_pool_res, y_pool_res = smote.fit_resample(X_pool_scaled, y_pool_raw)

print(f"Pooled training set after SMOTE: {X_pool_res.shape[0]} rows")
print(f"Post-SMOTE class distribution:\n{pd.Series(y_pool_res).value_counts()}")

# ==========================================
# STEP 5: Train pooled Logistic Regression
# Same hyperparameters/solver/epoch-logging style as your E1 LR script:
# multinomial, saga solver, warm_start, random_state=42, epoch step=100,
# max epochs=1000, with early-stop-on-convergence logging.
# ==========================================
print("\n--- [E3-LR STEP 5] Training pooled Logistic Regression ---")

EPOCHS_STEP = 100
MAX_EPOCHS = 1000

pooled_lr = LogisticRegression(
    multi_class='multinomial',
    solver='saga',
    warm_start=True,
    random_state=42,
    max_iter=EPOCHS_STEP
)

for current_max in range(EPOCHS_STEP, MAX_EPOCHS + 1, EPOCHS_STEP):
    pooled_lr.max_iter = current_max
    pooled_lr.fit(X_pool_res, y_pool_res)

    y_proba = pooled_lr.predict_proba(X_pool_res)
    classes = pooled_lr.classes_
    y_onehot = pd.get_dummies(y_pool_res)[classes].values
    loss = -np.mean(np.sum(y_onehot * np.log(y_proba + 1e-15), axis=1))

    print(f"  Epoch [{current_max:4d}/{MAX_EPOCHS}] - Loss: {loss:.4f} - Converged Iterations: {pooled_lr.n_iter_[0]}")

    if pooled_lr.n_iter_[0] < current_max:
        print(f"  --> Solver converged early at iteration {pooled_lr.n_iter_[0]}. Stopping epoch loop.")
        break

print("\nPooled Logistic Regression training complete.")

# ==========================================
# STEP 6: Evaluate pooled LR on ALL FOUR season test sets
# ==========================================
print("\n--- [E3-LR STEP 6] Evaluating pooled model on each season's test set ---")

results = []
evaluation_logs = {}

for season in seasons:
    X_te = season_test_sets[season]['X_test_scaled']
    y_te = season_test_sets[season]['y_test_raw']

    y_pred = pooled_lr.predict(X_te)
    y_proba = pooled_lr.predict_proba(X_te)

    macro_f1 = f1_score(y_te, y_pred, average='macro')
    g_mean = calc_gmean(y_te, y_pred)

    try:
        macro_auc = roc_auc_score(y_te, y_proba, multi_class='ovr', average='macro')
    except ValueError:
        macro_auc = np.nan

    cm = confusion_matrix(y_te, y_pred)
    evaluation_logs[season] = {'y_true': y_te, 'y_pred': y_pred, 'cm': cm}

    results.append({
        'Model': 'Logistic Regression',
        'Training Data': 'Pooled (Universal)',
        'Test Season': season.capitalize(),
        'Macro F1': round(macro_f1, 4),
        'Macro AUC': round(macro_auc, 4),
        'G-Mean': round(g_mean, 4)
    })

    print(f"Test={season.capitalize():<12} | Macro F1: {macro_f1:.4f} | Macro AUC: {macro_auc:.4f} | G-Mean: {g_mean:.4f}")

# ==========================================
# STEP 7: Export results
# ==========================================
tables_dir = os.path.join("results", "tables", "e3")
os.makedirs(tables_dir, exist_ok=True)

results_df = pd.DataFrame(results)
csv_path = os.path.join(tables_dir, "e3_pooled_logistic_regression.csv")
results_df.to_csv(csv_path, index=False)

print("\n=== E3: Pooled Logistic Regression Results ===")
print(results_df.to_string(index=False))
print(f"\n[SUCCESS] Exported E3 LR results to: {csv_path}")